version: '3.8'

services:
  postgres:
    image: postgres:17.2-alpine
    environment:
      POSTGRES_USER: openchat
      POSTGRES_PASSWORD: password
      POSTGRES_DB: openchat
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root" ]
      interval: 5s
      timeout: 2s

  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "3000:3000"
